[package]
name = "mkd"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
askama.workspace = true
askama-markdown-cmark.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
serde-wasm-bindgen.workspace = true
